export const SHOW_QUOTES = "SHOW_QUOTES";
export const SHOW_JOBS = "SHOW_JOBS";
export const SHOW_INVOICES = "SHOW_INVOICES";
export const SHOW_PURCHASES = "SHOW_PURCHASES";
export const SHOW_ADD_FORMS = "SHOW_ADD_FORMS";
export const SHOW_ADD_JOBS = "SHOW_ADD_JOB";
export const SHOW_ADD_COST_ITMES = "SHOW_ADD_COST_ITEMS";
export const SHOW_ADD_JOB_PROJECTS = "SHOW_ADD_JOB_PROJECTS";
export const SHOW_FILES_AND_NOTES = "SHOW_FILES_AND_NOTES";
export const SHOW_FORMS = "SHOW_FORMS";
export const SELECT_JOB_DUE_DATE = "SELECT_JOB_DUE_DATE";
export const SELECT_JOB_START_DATE = "SELECT_JOB_START_DATE";
export const SELECT_JOB_End_DATE = "SELECT_JOB_End_DATE";

/* types for view job page and its related stuff*/
export const SHOW_VIEW_JOB_COST_ITEMS = "SHOW_COST_ITEMS";
export const SHOW_VIEW_JOB_PROJECT_JOBS = "SHOW_PROJECT_JOBS";
export const SHOW_VIEW_JOB_FILES_AND_NOTES = "SHOW_VIEW_JOB_FILES_AND_NOTES";
export const SHOW_VIEW_JOB_FORMS = "SHOW_VIEW_JOB_FORMS";
export const SHOW_VIEW_JOB_JOB_ACTIVITY = "SHOW_VIEW_JOB_JOB_ACTIVITY";
export const SHOW_VIEW_JOB = "SHOW_VIEW_JOB";

/* END TYPES FOR VIEW JOB PAGE */

/* starting types for subscription page */

export const INCREASE_NUMBER_OF_USERS_BY_ONE =
  "INCREASE_NUMBER_OF_USERS_BY_ONE";
export const DECREASE_NUMBER_OF_USERS_BY_ONE =
  "DECREASE_NUMBER_OF_USERS_BY_ONE";
export const SET_NUMBER_OF_USERS = "SET_NUMBER_OF_USERS";
